keycloak:
  realm: springboot-microservice-realm
  domain: localhost:9090
  adminClientId: admin-cli
  adminClientSecret: FxxojtM3fNG48heZFubxGFuVgKTdjXyR
  client: microservice-auth
  urls:
    auth: http://${keycloak.domain}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/springboot-microservice-realm
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: microservice-auth
logging:
  level:
    org:
      springframework:
        web: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: '8085'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: '1.0'